/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobilfinal;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rentalmobilfinal.koneksi.conn;

/**
 *
 * @author Kalingga Padel
 */
public class panelPetugas1_CS extends javax.swing.JPanel {

    /**
     * Creates new form panelPetugas
     */
    
    private void tampilData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Petugas");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jabatan");
        model.addColumn("Gaji");
        model.addColumn("Username");
        model.addColumn("Password");
        jTable1.setModel(model);
        
            try {
        Connection con = new conn().conn();
        java.sql.Statement stat = con.createStatement();
        ResultSet data = stat.executeQuery("SELECT * FROM Petugas");
        
        while (data.next()) {
            model.addRow(new Object[]{
                data.getString("idPetugas"),
                data.getString("namaPetugas"),
                data.getString("jenisKelamin"),
                data.getString("jabatan"),
                data.getString("gaji"),
                data.getString("username"),
                data.getString("password")
            });
            jTable1.setModel(model);
        }
    } catch (Exception e) {
        System.err.println("Terjadi Kesalahan :" + e);
    }
    
        
    }
    
    public panelPetugas1_CS() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idPtg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        namaPtg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jabatanPtg = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        userPtg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jkPtg = new javax.swing.JComboBox<>();
        pwdPtg = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 116, 255));
        jLabel1.setText("DATA | PETUGAS");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setText("* ID Petugas");

        idPtg.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        idPtg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idPtg.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel7.setText("* Nama Lengkap");

        namaPtg.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        namaPtg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel10.setText("* Jabatan");

        jabatanPtg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "CEO" }));
        jabatanPtg.setBorder(null);
        jabatanPtg.setLightWeightPopupEnabled(false);
        jabatanPtg.setRequestFocusEnabled(false);

        jButton3.setBackground(new java.awt.Color(110, 116, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SIMPAN");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(110, 116, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CARI");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel11.setText("* Username");

        userPtg.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        userPtg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel12.setText("* Password");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel13.setText("* Jenis Kelamin");

        jkPtg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        jkPtg.setBorder(null);
        jkPtg.setLightWeightPopupEnabled(false);
        jkPtg.setRequestFocusEnabled(false);

        pwdPtg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(idPtg)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(198, 198, 198))
                                    .addComponent(jLabel11)
                                    .addComponent(userPtg)
                                    .addComponent(pwdPtg))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaPtg)
                                    .addComponent(jabatanPtg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jkPtg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13))
                                        .addGap(0, 173, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(namaPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jkPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jabatanPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id                  = 0;
        String nama             = namaPtg.getText();
        String jk               = (String)jkPtg.getSelectedItem();
        String jabatan          = (String)jabatanPtg.getSelectedItem();
        int gaji                = 0;
        if(jabatan.equals("CEO")){
            gaji = 5000000;
        }else{
            gaji = 3000000;
        }
        String user             = userPtg.getText();
        String pwd              = pwdPtg.getText();
        
        try {
            Connection con = new conn().conn();
            java.sql.Statement stat = con.createStatement();
            String sql = "INSERT INTO petugas VALUES ('"+ id +"','"+ nama +"','"+ jk +"','"+ jabatan +"','"+ gaji +"','"+ user +"','"+ pwd + "')";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil DI Tambah","Perhatian",JOptionPane.WARNING_MESSAGE);
            tampilData();

        idPtg.setText("");
        namaPtg.setText("");
        jkPtg.setSelectedItem(1);
        jabatanPtg.setSelectedItem(1);
        userPtg.setText("");
        pwdPtg.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(panelCs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            
            idPtg.setText(jTable1.getValueAt(baris, 0).toString());
            namaPtg.setText(jTable1.getValueAt(baris, 1).toString());
            jkPtg.setSelectedItem(jTable1.getValueAt(baris, 2).toString());
            jabatanPtg.setSelectedItem(jTable1.getValueAt(baris, 3).toString());
            userPtg.setText(jTable1.getValueAt(baris, 5).toString());
            pwdPtg.setText(jTable1.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nama = namaPtg.getText();
        try {
            Connection con = new conn().conn();
            java.sql.Statement stat = con.createStatement();
            String sql = "SELECT * FROM petugas WHERE namaPetugas = '"+ nama +"'";
            ResultSet data = stat.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Petugas");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Jabatan");
            model.addColumn("Gaji");
            model.addColumn("Username");
            model.addColumn("Password");
            jTable1.setModel(model);

            if(data.next()){
            model.addRow(new Object[]{
                data.getString("idPetugas"),
                data.getString("namaPetugas"),
                data.getString("jenisKelamin"),
                data.getString("jabatan"),
                data.getString("gaji"),
                data.getString("username"),
                data.getString("password")
            });
            jTable1.setModel(model);

            }else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ada","Perhatian",JOptionPane.WARNING_MESSAGE);
                tampilData();
            }

        }catch (SQLException ex) {
            Logger.getLogger(panelCs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idPtg;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jabatanPtg;
    private javax.swing.JComboBox<String> jkPtg;
    private javax.swing.JTextField namaPtg;
    private javax.swing.JPasswordField pwdPtg;
    private javax.swing.JTextField userPtg;
    // End of variables declaration//GEN-END:variables
}
