/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobilfinal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import rentalmobilfinal.koneksi.conn;
import rentalmobilfinal.panelPinjam;

/**
 *
 * @author Kalingga Padel
 */
public class panelKembali_CS extends javax.swing.JPanel {

    /**
     * Creates new form panelKembali
     */
    
    private void tampilData(){
        
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No Transaksi");
        model.addColumn("Tgl Kembali");
        model.addColumn("Petugas");
        model.addColumn("Customer");
        model.addColumn("No Pinjam");
        model.addColumn("No Pol");
        model.addColumn("Nama Kendaraan");
        model.addColumn("Jenis");
        model.addColumn("Harga Sewa");
        model.addColumn("Denda");
        model.addColumn("Total");
        jTable1.setModel(model);
        
        try {
            Connection con = new conn().conn();
            java.sql.Statement stat = con.createStatement();
            String sql              = "SELECT * FROM fkembali";
            ResultSet data          = stat.executeQuery(sql);
            
            while(data.next()){
                model.addRow(new Object[]{
                    data.getString("NoTransaksi"),
                    data.getString("tglKembali"),
                    data.getString("Petugas"),
                    data.getString("Customer"),
                    data.getString("NoPinjam"),
                    data.getString("noPol"),
                    data.getString("nama"),
                    data.getString("jenis"),
                    data.getString("hargaSewa"),
                    data.getString("namaDenda"),
                    data.getString("Total"),
                    
                });
            }
                
            
            
        } catch (Exception e) {
                
                }
        }
    
    private void tampilcbPetugas(){
        Connection con = new conn().conn();
        try {
            java.sql.Statement stat = con.createStatement();
            String sql = "SELECT namaPetugas From Petugas";
            ResultSet data = stat.executeQuery(sql);
            idPtg.addItem("PILIH PETUGAS");
            while(data.next()){
                idPtg.addItem(data.getString("namaPetugas"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelKembali_CS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
        private void tampilcbDenda(){
        Connection con = new conn().conn();
        try {
            java.sql.Statement stat = con.createStatement();
            String sql = "SELECT namaDenda From denda";
            ResultSet data = stat.executeQuery(sql);
            cbDenda.addItem("Pilih Denda");
            while(data.next()){
                cbDenda.addItem(data.getString("namaDenda"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelKembali_CS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
        

    
    public panelKembali_CS() {
        initComponents();
        tampilData();
        tampilcbPetugas();
        tampilcbDenda();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tglKembali = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        idPtg = new javax.swing.JComboBox<>();
        trxId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbDenda = new javax.swing.JComboBox<>();
        dDenda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        noPeminjaman = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hargaDenda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Csname = new javax.swing.JTextField();
        lamaPinjam = new javax.swing.JTextField();
        noPol = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hargaA = new javax.swing.JTextField();
        tglPinjam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 116, 255));
        jLabel1.setText("DATA | PENGEMBALIAN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setText("* Tanggaal Kembali");

        tglKembali.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel7.setText("* Petugas");

        idPtg.setBorder(null);

        trxId.setEditable(false);
        trxId.setBackground(new java.awt.Color(255, 255, 255));
        trxId.setForeground(new java.awt.Color(255, 255, 255));
        trxId.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel11.setText("* Customer");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel12.setText("* No Polisi");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel13.setText("* Denda");

        cbDenda.setBorder(null);
        cbDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDendaActionPerformed(evt);
            }
        });

        dDenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel14.setText("* No Peminjaman");

        noPeminjaman.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel8.setText("* Lama Pinjam");

        hargaDenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel15.setText("* Harga");

        jButton3.setBackground(new java.awt.Color(110, 116, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CEK");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(110, 116, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SIMPAN");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Csname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Csname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Csname.setEnabled(false);

        lamaPinjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lamaPinjam.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lamaPinjam.setEnabled(false);

        noPol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        noPol.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        noPol.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel9.setText("* Harga");

        hargaA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hargaA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        hargaA.setEnabled(false);

        tglPinjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tglPinjam.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tglPinjam.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel10.setText("* Tanggal Pinjam");

        jButton7.setBackground(new java.awt.Color(110, 116, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CETAK");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(62, 62, 62)
                                .addComponent(trxId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(idPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lamaPinjam)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noPol, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hargaA, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(tglPinjam)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Csname, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(trxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPtg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(noPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Csname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noPol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hargaA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dDenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(cbDenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaDenda, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            trxId.setText(jTable1.getValueAt(baris, 0).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con = new conn().conn();
        
        
        try {
            String noTrxp = noPeminjaman.getText();
            
            java.sql.Statement stat = con.createStatement();
            String sqlcek       = "SELECT NoPinjam FROM kembali WHERE NoPinjam = '"+ noTrxp +"'";
            ResultSet datacek   = stat.executeQuery(sqlcek);
            if(datacek.next()){
                JOptionPane.showMessageDialog(null, "Mobil Sudah Di Kembalikan","Perhatian",JOptionPane.WARNING_MESSAGE);
            }else{
                

                String sql = "SELECT * FROM pinjam WHERE noTransaksi = '"+ noTrxp +"'";
                ResultSet data = stat.executeQuery(sql);
                while(data.next()){
                    noPol.setText(data.getString("noPol"));
                    tglPinjam.setText(data.getString("tglPeminjaman"));
                    Csname.setText(data.getString("nama"));
                    lamaPinjam.setText(data.getString("lamaPinjam"));
                    hargaA.setText(data.getString("total"));
                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            int noTrx = 0;
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal  = format.format(tglKembali.getDate());

            String idPtgs   = idPtg.getSelectedItem().toString();
            String idCss    = Csname.getText();
            String noBe     = noPol.getText();
            String noPinjam = noPeminjaman.getText();
            String idDenda  = cbDenda.getSelectedItem().toString();
            int hargaA   = new Integer(this.hargaA.getText());
            int HargaD   = new Integer(hargaDenda.getText());
            int lamaD    = new Integer(dDenda.getText());
            int total     = hargaA + (HargaD * lamaD);
            System.out.println(total);

            Connection con = new conn().conn();

            java.sql.Statement stat = con.createStatement();
            String sqlPetugas       = "SELECT idPetugas FROM petugas WHERE namaPetugas = '"+ idPtgs +"'";
            ResultSet dataPetugas          = stat.executeQuery(sqlPetugas);
            dataPetugas.next();
            int  idPtgasF = new Integer(dataPetugas.getString("idPetugas"));

            String sqlCs            = "SELECT idCs FROM customer WHERE nama = '"+ idCss +"'";
            ResultSet dataCs        = stat.executeQuery(sqlCs);
            dataCs.next();
            int  idCsF = new Integer(dataCs.getString("idCs"));
//
            String sqlD           = "SELECT idDenda FROM denda WHERE namaDenda = '"+ idDenda +"'";
            ResultSet dataD       = stat.executeQuery(sqlD);
            dataD.next();
            String  idD = dataD.getString("idDenda");
            
//            System.out.println(tanggal);
//            System.out.println(idPtgasF);
//            System.out.println(idCsF);
//            System.out.println(noBe);
//            System.out.println(noPinjam);
//            System.out.println(idD);
//            System.out.println(total);
//

//
            String sqlPinjam        = "INSERT INTO pengembalian VALUES ('"+ noTrx +"','"+ tanggal +"','"+ idPtgasF +"','"+ idCsF +"','"+ noBe +"','"+ noPinjam +"','"+ idD+"','"+ total +"')";
            stat.executeUpdate(sqlPinjam);
//
            String sqlupdate        = "UPDATE kendaraan SET status = 'Tersedia' WHERE noPol = '"+ noBe +"'";
            stat.executeUpdate(sqlupdate);
            JOptionPane.showMessageDialog(null, "Data Berhasil DI Simpan","Perhatian",JOptionPane.WARNING_MESSAGE);
            tampilData();
            panelPinjam coba = new panelPinjam();
            coba.tampilcbNopol();
//
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void cbDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDendaActionPerformed
        if (cbDenda.getSelectedItem().equals("Telat Pengembalian")) {
            hargaDenda.setText("200000");
        }else if(cbDenda.getSelectedItem().equals("Rusak Ringan")){
            hargaDenda.setText("700000");
        }else if(cbDenda.getSelectedItem().equals("Rusak Sedang")){
            hargaDenda.setText("1200000");
        }else if(cbDenda.getSelectedItem().equals("Rusak Berat")){
            hargaDenda.setText("3000000");
        }else if(cbDenda.getSelectedItem().equals("Tidak Ada")){
            hargaDenda.setText("0");
        }
    }//GEN-LAST:event_cbDendaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            String NamaFile = "C:\\Users\\Kalingga Padel\\Documents\\NetBeansProjects\\rentalMobilfinal\\src\\rentalmobilfinal\\notaK.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/rental","root","");
            HashMap param = new HashMap();
            param.put("notrx",trxId.getText());
                   
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint);
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Csname;
    private javax.swing.JComboBox<String> cbDenda;
    private javax.swing.JTextField dDenda;
    private javax.swing.JTextField hargaA;
    private javax.swing.JTextField hargaDenda;
    private javax.swing.JComboBox<String> idPtg;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lamaPinjam;
    private javax.swing.JTextField noPeminjaman;
    private javax.swing.JTextField noPol;
    private com.toedter.calendar.JDateChooser tglKembali;
    private javax.swing.JTextField tglPinjam;
    private javax.swing.JTextField trxId;
    // End of variables declaration//GEN-END:variables
}
